### PR TITLE
Update install

### PR DESCRIPTION
**Pull request by Ddataa**
## Problem

- I am tired to manually copy and paste certificates on my server....also https://github.com/YunoHost-Apps/adguardhome_ynh/issues/67

## Solution

- apply group ssl-cert to user adguardhome

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Ddataa** [comment]
!gogogadgetoci

**Comment by MohamedElashri** [comment]
Can you also add the same thing into `upgrade` script so that the same happens when upgrading the package 
https://github.com/YunoHost-Apps/adguardhome_ynh/blob/a7c5b32098bc431393a07d7e7f43f8978fef368a/scripts/upgrade#L101

**Comment by Ddataa** [comment]
merging ?!

**Review by ericgaspar — APPROVED** [review]

**Comment by MohamedElashri** [comment]
Is there any tentative time frame for merging this into main?

**Pull request merged**
